#!/bin/bash
touch index.md
touch home.md
touch accounts.index.md
touch accounts.create.md
touch accounts.edit.md
touch accounts.delete.md
touch accounts.show.md
touch accounts.show.date.md
touch attachments.edit.md
touch attachments.delete.md
touch attachments.preview.md
touch attachments.download.md
touch bills.index.md
touch bills.rescan.md
touch bills.create.md
touch bills.edit.md
touch bills.delete.md
touch bills.show.md
touch budgets.index.md
touch budgets.income.md
touch budgets.create.md
touch budgets.edit.md
touch budgets.delete.md
touch budgets.show.md
touch budgets.showWithRepetition.md
touch budgets.noBudget.md
touch categories.index.md
touch categories.create.md
touch categories.edit.md
touch categories.delete.md
touch categories.show.md
touch categories.show.date.md
touch categories.noCategory.md
touch currency.index.md
touch currency.create.md
touch currency.edit.md
touch currency.delete.md
touch currency.default.md
touch export.index.md
touch export.status.md
touch export.download.md
touch import.index.md
touch import.configure.md
touch import.settings.md
touch import.complete.md
touch import.download.md
touch import.status.md
touch import.finished.md
touch new-user.index.md
touch piggy-banks.index.md
touch piggy-banks.create.md
touch piggy-banks.edit.md
touch piggy-banks.delete.md
touch piggy-banks.show.md
touch preferences.md
touch profile.md
touch profile.change-password.md
touch profile.delete-account.md
touch reports.index.md
touch reports.report.md
touch reports.data.accountReport.md
touch rules.index.md
touch rules.rule.create.md
touch rules.rule.edit.md
touch rules.rule.delete.md
touch rules.rule.test_triggers.md
touch rules.rule-group.create.md
touch rules.rule-group.edit.md
touch rules.rule-group.delete.md
touch rules.rule-group.select_transactions.md
touch search.md
touch tags.index.md
touch tags.create.md
touch tags.show.md
touch tags.edit.md
touch tags.delete.md
touch transactions.index.md
touch transactions.show.md
touch transactions.create.md
touch transactions.edit.md
touch transactions.delete.md
touch transactions.mass-edit.md
touch transactions.mass-delete.md
touch transactions.edit-split.md
touch admin.index.md
touch admin.users.md
touch admin.users.edit.md
touch admin.users.show.md
touch admin.users.domains.md
touch admin.configuration.index.md
