#!/bin/bash
touch index.md
touch home.md
touch accounts.index.md
touch accounts.create.md
touch accounts.edit.md
touch accounts.delete.md
touch accounts.show.md
touch accounts.show.all.md
touch accounts.show.date.md
touch attachments.edit.md
touch attachments.delete.md
touch bills.index.md
touch bills.create.md
touch bills.edit.md
touch bills.delete.md
touch bills.show.md
touch budgets.index.md
touch budgets.create.md
touch budgets.edit.md
touch budgets.delete.md
touch budgets.show.md
touch budgets.show.repetition.md
touch budgets.no-budget.md
touch categories.index.md
touch categories.create.md
touch categories.edit.md
touch categories.delete.md
touch categories.show.md
touch categories.show.date.md
touch categories.no-category.md
touch currencies.index.md
touch currencies.create.md
touch currencies.edit.md
touch currencies.delete.md
touch currencies.default.md
touch export.index.md
touch export.status.md
touch export.download.md
touch import.index.md
touch import.configure.md
touch import.settings.md
touch import.complete.md
touch import.download.md
touch import.status.md
touch import.finished.md
touch new-user.index.md
touch piggy-banks.index.md
touch piggy-banks.create.md
touch piggy-banks.edit.md
touch piggy-banks.delete.md
touch piggy-banks.show.md
touch preferences.index.md
touch preferences.code.md
touch preferences.delete-code.md
touch profile.index.md
touch profile.change-password.md
touch profile.delete-account.md
touch reports.index.md
touch reports.options.md
touch reports.report.default.md
touch reports.report.audit.md
touch reports.report.category.md
touch reports.report.budget.md
touch rules.index.md
touch rules.create.md
touch rules.up.md
touch rules.down.md
touch rules.edit.md
touch rules.delete.md
touch rules.test-triggers.md
touch rule-groups.create.md
touch rule-groups.edit.md
touch rule-groups.delete.md
touch rule-groups.up.md
touch rule-groups.down.md
touch rule-groups.select-transactions.md
touch search.index.md
touch tags.index.md
touch tags.create.md
touch tags.show.md
touch tags.edit.md
touch tags.delete.md
touch transactions.index.md
touch transactions.index.all.md
touch transactions.index.date.md
touch transactions.show.md
touch transactions.create.md
touch transactions.edit.md
touch transactions.delete.md
touch transactions.massedit.md
touch transactions.massdelete.md
touch transactions.split.edit.md
touch transactions.convert.index.md
touch admin.index.md
touch admin.users.md
touch admin.users.edit.md
touch admin.users.show.md
touch admin.users.domains.md
touch admin.configuration.index.md
