#!/bin/bash
touch index.md
touch home.md
touch accounts_index.md
touch accounts_create.md
touch accounts_edit.md
touch accounts_delete.md
touch accounts_show.md
touch accounts_show_date.md
touch attachments_edit.md
touch attachments_delete.md
touch attachments_preview.md
touch attachments_download.md
touch bills_index.md
touch bills_rescan.md
touch bills_create.md
touch bills_edit.md
touch bills_delete.md
touch bills_show.md
touch budgets_index.md
touch budgets_income.md
touch budgets_create.md
touch budgets_edit.md
touch budgets_delete.md
touch budgets_show.md
touch budgets_showWithRepetition.md
touch budgets_noBudget.md
touch categories_index.md
touch categories_create.md
touch categories_edit.md
touch categories_delete.md
touch categories_show.md
touch categories_show_date.md
touch categories_noCategory.md
touch currency_index.md
touch currency_create.md
touch currency_edit.md
touch currency_delete.md
touch currency_default.md
touch export_index.md
touch export_status.md
touch export_download.md
touch import_index.md
touch import_configure.md
touch import_settings.md
touch import_complete.md
touch import_download.md
touch import_status.md
touch import_json.md
touch import_finished.md
touch help_show.md
touch new-user_index.md
touch piggy-banks_index.md
touch piggy-banks_create.md
touch piggy-banks_edit.md
touch piggy-banks_delete.md
touch piggy-banks_show.md
touch preferences.md
touch profile.md
touch profile_change-password.md
touch profile_delete-account.md
touch reports_index.md
touch reports_report.md
touch reports_data_accountReport.md
touch rules_index.md
touch rules_rule_create.md
touch rules_rule_edit.md
touch rules_rule_delete.md
touch rules_rule_test_triggers.md
touch rules_rule-group_create.md
touch rules_rule-group_edit.md
touch rules_rule-group_delete.md
touch rules_rule-group_select_transactions.md
touch search.md
touch tags_index.md
touch tags_create.md
touch tags_show.md
touch tags_edit.md
touch tags_delete.md
touch transactions_index.md
touch transactions_show.md
touch transactions_create.md
touch transactions_edit.md
touch transactions_delete.md
touch transactions_mass-edit.md
touch transactions_mass-delete.md
touch transactions_edit-split.md
touch admin_index.md
touch admin_users.md
touch admin_users_edit.md
touch admin_users_show.md
touch admin_users_domains.md
touch admin_configuration_index.md